In [183]:
from IPython.lib.deepreload import reload
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [184]:
import klimDataRetriever as klimData

In [185]:
kIndDf = klimData.klimDataRetriever(debug=True)

Cite this module as Karunakar, "HBRC (2021): A python module to fetch Climate indices-Ver $version_number"
Along with the link where the code is sourced from, this will help users to check if there are any updates
for others please refer to
SOI: https://crudata.uea.ac.uk/cru/data/soi/
IPO: https://psl.noaa.gov/data/timeseries/IPOTPI/
SAM : https://climatedataguide.ucar.edu/climate-data/marshall-southern-annular-mode-sam-index-station-based
SPSD : https://www.hbrc.govt.nz/assets/Document-Library/Publications-Database/4914-RM17-01-Hawkes-Bay-Seasonal-Forecasting.pdf
IOD: https://psl.noaa.gov/gcos_wgsp/Timeseries/DMI/
STR: HBRC (based on Cai et.al. 2011)

In [186]:
kIndDf.getClimData()

mean SLP of {'lat': (-10, -50), 'lon': (165, 180)} 1012.8687
nan patching missing dates

[Timestamp('2021-08-01 00:00:00'),
 Timestamp('2021-09-01 00:00:00'),
 Timestamp('2021-10-01 00:00:00'),
 Timestamp('2021-11-01 00:00:00'),
 Timestamp('2021-12-01 00:00:00')]

     year    Annual                                                   \
               strp      stri       sps   soi       ipo          iod
0    1854       NaN       NaN       NaN   NaN -0.139000          NaN
1    1855       NaN       NaN       NaN   NaN  0.039909          NaN
2    1856       NaN       NaN       NaN   NaN -0.261455          NaN
3    1857       NaN       NaN       NaN   NaN -0.393545          NaN
4    1858       NaN       NaN       NaN   NaN  0.397455          NaN
..    ...       ...       ...       ...   ...       ...          ...
163  2017 -2.954545  0.941668  0.002695  0.11 -0.313727     0.377273
164  2018  0.227273 -0.453222  0.006032  0.07 -0.517091     0.287636
165  2019  0.227273  1.449203  0.008105 -0.81 -0.091273     0.660455
166  2020 -0.681818  1.751214  0.000330  0.31 -0.754455     0.194545
167  2021 -0.833333  0.408892       NaN   NaN -1.011571 -5453.889091

               Apr            ...    hydYrAvg           state            \
          aao strp      stri  ...         iod       aao  strp stri  sps
0         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
1         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
2         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
3         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
4         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
..        ...  ...       ...  ...         ...       ...   ...  ...  ...
163  0.464545 -5.0 -0.588943  ...    0.215583  0.446667   Neg  Pos  Pos
164  0.699091  2.5 -1.095762  ...    0.490333  1.165833   Neg  Pos  Pos
165 -0.406364  0.0  3.179960  ...    0.511167 -0.737500   Pos  Neg  Pos
166  0.205455  2.5 -0.098447  ... -833.086750  0.706667   Neg  Pos  Pos
167  0.804286  2.5 -1.721084  ...         NaN       NaN   Neg  Pos  NaN

                             datetime
        soi  ipo  iod  aao
0       NaN  Neg  NaN  NaN 1854-07-01
1       NaN  Pos  NaN  NaN 1855-07-01
2       NaN  Neg  NaN  NaN 1856-07-01
3       NaN  Pos  NaN  NaN 1857-07-01
4       NaN  Neg  NaN  NaN 1858-07-01
..      ...  ...  ...  ...        ...
163  LaNina  Neg  Pos  Pos 2017-07-01
164  ElNino  Neg  Pos  Pos 2018-07-01
165  ElNino  Neg  Pos  Neg 2019-07-01
166  LaNina  Neg  Neg  Pos 2020-07-01
167  LaNina  Pos  Pos  Pos 2021-07-01

[168 rows x 135 columns]

In [187]:
kIndDf.getSelectSeries()

,strp,stri,sps,soi,ipo,iod,aao,datetime,year
0,NaN,NaN,NaN,NaN,-0.401417,NaN,NaN,1854-07-01,1854
1,NaN,NaN,NaN,NaN,0.235333,NaN,NaN,1855-07-01,1855
2,NaN,NaN,NaN,NaN,-0.739583,NaN,NaN,1856-07-01,1856
3,NaN,NaN,NaN,NaN,0.148250,NaN,NaN,1857-07-01,1857
4,NaN,NaN,NaN,NaN,-0.084250,NaN,NaN,1858-07-01,1858
...,...,...,...,...,...,...,...,...,...
163,-1.666667,1.323033,0.007588,0.355833,-0.775667,0.215583,0.446667,2017-07-01,2017
164,-1.666667,0.509853,0.006835,-0.437500,-0.034500,0.490333,1.165833,2018-07-01,2018
165,0.416667,-0.296005,0.002938,-0.543333,-0.266083,0.511167,-0.737500,2019-07-01,2019
166,-0.833333,2.183801,NaN,NaN,-1.150000,-833.086750,0.706667,2020-07-01,2020
167,-0.208333,0.718039,NaN,NaN,NaN,NaN,NaN,2021-07-01,2021

In [188]:
kIndDf.getSelectSeries().dropna()

,strp,stri,sps,soi,ipo,iod,aao,datetime,year
103,-0.833333,-0.697973,0.074651,-0.690833,0.760667,-0.326167,-1.707500,1957-07-01,1957
104,-1.041667,-0.640029,0.400702,-0.295000,0.187917,-0.637583,0.029167,1958-07-01,1958
105,-1.875000,0.695096,0.308627,0.140000,-0.102417,-0.469333,0.622500,1959-07-01,1959
106,0.000000,-0.227266,0.007102,0.099167,-0.159417,-0.373417,0.050833,1960-07-01,1960
107,-2.291667,0.651960,0.768081,0.345833,-0.741333,0.398583,0.425833,1961-07-01,1961
...,...,...,...,...,...,...,...,...,...
161,-1.041667,1.743972,0.159137,-1.305000,1.106167,0.258833,1.660833,2015-07-01,2015
162,0.833333,0.778421,0.312949,-0.026667,-0.255500,0.025750,-0.155000,2016-07-01,2016
163,-1.666667,1.323033,0.007588,0.355833,-0.775667,0.215583,0.446667,2017-07-01,2017
164,-1.666667,0.509853,0.006835,-0.437500,-0.034500,0.490333,1.165833,2018-07-01,2018
165,0.416667,-0.296005,0.002938,-0.543333,-0.266083,0.511167,-0.737500,2019-07-01,2019

In [189]:
kIndDf.getAAOdata()

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,...,Nov,Dec,Annual,hydYrAvg,JJA,SON,DJF,MAM,state,datetime
0,1957,-0.87,-2.27,0.07,-1.97,-2.50,-0.87,1.00,-1.73,0.72,...,-5.42,-2.63,-1.541818,-1.707500,-0.533333,-2.606667,-1.570000,-1.466667,Neg,1957-07-01
1,1958,0.04,-2.84,-2.52,-0.30,-2.72,-0.97,-1.65,0.97,1.90,...,0.30,0.82,-0.722727,0.029167,-0.550000,0.680000,-1.810000,-1.846667,Pos,1958-07-01
2,1959,1.59,-0.19,-0.54,-1.25,-0.32,-1.12,0.18,-1.64,2.46,...,3.28,-0.38,0.180909,0.622500,-0.860000,1.760000,0.740000,-0.703333,Pos,1959-07-01
3,1960,0.90,0.85,3.40,-0.35,-0.60,-0.17,0.31,0.43,1.41,...,1.18,1.36,0.562727,0.050833,0.190000,0.473333,0.456667,0.816667,Pos,1960-07-01
4,1961,0.91,-4.00,-0.40,-0.14,1.12,-0.40,0.98,1.10,-1.21,...,1.52,2.32,0.101818,0.425833,0.560000,0.650000,-0.576667,0.193333,Pos,1961-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2017,-1.12,-1.09,-1.56,1.65,1.82,1.98,0.16,0.31,0.42,...,3.18,1.44,0.464545,0.446667,0.816667,0.986667,-1.243333,0.636667,Pos,2017-07-01
61,2018,2.72,1.02,-0.03,-1.66,0.01,-1.57,0.55,-0.78,1.83,...,2.84,1.44,0.699091,1.165833,-0.600000,2.476667,1.726667,-0.560000,Pos,2018-07-01
62,2019,2.79,-1.87,1.47,0.86,-0.11,2.21,-2.20,-2.04,0.81,...,-4.42,-1.78,-0.406364,-0.737500,-0.676667,-1.860000,0.786667,0.740000,Neg,2019-07-01
63,2020,0.57,-0.36,2.05,-1.72,1.03,1.18,-0.97,-2.20,-0.25,...,1.14,2.28,0.205455,0.706667,-0.663333,0.893333,-0.523333,0.453333,Pos,2020-07-01
64,2021,1.95,2.19,-0.95,0.87,0.75,1.88,-1.06,NaN,NaN,...,NaN,NaN,0.804286,NaN,0.410000,NaN,2.140000,0.223333,Pos,2021-07-01

In [190]:
kIndDf.getAAOdata()

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,...,Nov,Dec,Annual,hydYrAvg,JJA,SON,DJF,MAM,state,datetime
0,1957,-0.87,-2.27,0.07,-1.97,-2.50,-0.87,1.00,-1.73,0.72,...,-5.42,-2.63,-1.541818,-1.707500,-0.533333,-2.606667,-1.570000,-1.466667,Neg,1957-07-01
1,1958,0.04,-2.84,-2.52,-0.30,-2.72,-0.97,-1.65,0.97,1.90,...,0.30,0.82,-0.722727,0.029167,-0.550000,0.680000,-1.810000,-1.846667,Pos,1958-07-01
2,1959,1.59,-0.19,-0.54,-1.25,-0.32,-1.12,0.18,-1.64,2.46,...,3.28,-0.38,0.180909,0.622500,-0.860000,1.760000,0.740000,-0.703333,Pos,1959-07-01
3,1960,0.90,0.85,3.40,-0.35,-0.60,-0.17,0.31,0.43,1.41,...,1.18,1.36,0.562727,0.050833,0.190000,0.473333,0.456667,0.816667,Pos,1960-07-01
4,1961,0.91,-4.00,-0.40,-0.14,1.12,-0.40,0.98,1.10,-1.21,...,1.52,2.32,0.101818,0.425833,0.560000,0.650000,-0.576667,0.193333,Pos,1961-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2017,-1.12,-1.09,-1.56,1.65,1.82,1.98,0.16,0.31,0.42,...,3.18,1.44,0.464545,0.446667,0.816667,0.986667,-1.243333,0.636667,Pos,2017-07-01
61,2018,2.72,1.02,-0.03,-1.66,0.01,-1.57,0.55,-0.78,1.83,...,2.84,1.44,0.699091,1.165833,-0.600000,2.476667,1.726667,-0.560000,Pos,2018-07-01
62,2019,2.79,-1.87,1.47,0.86,-0.11,2.21,-2.20,-2.04,0.81,...,-4.42,-1.78,-0.406364,-0.737500,-0.676667,-1.860000,0.786667,0.740000,Neg,2019-07-01
63,2020,0.57,-0.36,2.05,-1.72,1.03,1.18,-0.97,-2.20,-0.25,...,1.14,2.28,0.205455,0.706667,-0.663333,0.893333,-0.523333,0.453333,Pos,2020-07-01
64,2021,1.95,2.19,-0.95,0.87,0.75,1.88,-1.06,NaN,NaN,...,NaN,NaN,0.804286,NaN,0.410000,NaN,2.140000,0.223333,Pos,2021-07-01

In [191]:
kIndDf = klimData.klimDataRetriever(SAM='AAO')
display(kIndDf.getAAOdata())

switching SAM source

,year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,...,Nov,Dec,Annual,hydYrAvg,JJA,SON,DJF,MAM,state,datetime
0,1979,0.209,0.356,0.899,0.678,0.724,1.700,2.412,0.546,0.629,...,-0.423,-0.951,0.717273,-0.228250,1.552667,0.122000,0.282500,0.767000,Neg,1979-07-01
1,1980,-0.447,-0.980,-1.424,-2.068,-0.479,0.286,-1.944,-0.997,-1.701,...,-2.013,-0.356,-1.017273,-0.715333,-0.885000,-1.045667,-0.792667,-1.323667,Neg,1980-07-01
2,1981,0.231,0.039,-0.966,-1.462,-0.344,0.352,-0.986,-2.118,-1.509,...,0.626,1.116,-0.581545,0.063667,-0.917333,-0.381000,-0.028667,-0.924000,Pos,1981-07-01
3,1982,-0.554,0.277,1.603,1.531,0.118,0.920,-0.415,0.779,1.580,...,-0.849,-1.934,0.389818,-0.362250,0.428000,0.009667,0.279667,1.084000,Neg,1982-07-01
4,1983,-1.340,-1.081,0.166,0.149,-0.437,-0.263,1.114,0.792,-0.696,...,0.727,0.475,0.029455,0.099917,0.547667,0.408000,-1.451667,-0.040667,Pos,1983-07-01
5,1984,-1.098,-0.544,0.251,-0.204,-1.237,0.426,0.890,-0.548,0.327,...,-0.024,-1.476,-0.160909,-0.160000,0.256000,0.098000,-0.389000,-0.396667,Neg,1984-07-01
6,1985,-0.795,0.215,-0.134,0.031,-0.066,-0.331,1.914,0.595,1.507,...,1.085,1.240,0.408364,0.171583,0.726000,1.021000,-0.685333,-0.056333,Pos,1985-07-01
7,1986,0.158,-1.588,-0.770,-0.087,-1.847,-0.619,0.089,-0.157,0.849,...,-0.222,0.886,-0.353455,-0.082417,-0.229000,0.311000,-0.063333,-0.901333,Neg,1986-07-01
8,1987,-0.950,-0.708,-0.133,-0.286,0.039,-0.702,-1.531,1.485,-0.799,...,1.060,0.272,-0.188182,-0.101583,-0.249333,0.238667,-0.257333,-0.126667,Neg,1987-07-01
9,1988,-0.612,0.551,-0.219,-0.077,-0.749,-1.055,0.576,-0.745,-0.689,...,0.401,1.074,-0.448364,0.376250,-0.408000,-0.867333,0.070333,-0.348333,Pos,1988-07-01
10,1989,0.618,0.849,0.632,-0.573,2.691,1.995,1.458,-0.132,-0.121,...,0.572,-0.445,0.738636,-0.075667,1.107000,0.195667,0.847000,0.916667,Neg,1989-07-01
11,1990,-0.352,1.151,0.414,-1.879,-1.803,0.093,-1.215,0.466,1.482,...,-0.359,-0.312,-0.169364,-0.132750,-0.218667,0.420667,0.118000,-1.089333,Neg,1990-07-01
12,1991,0.869,-0.852,0.522,-0.639,-0.539,-1.155,-1.220,0.036,-0.513,...,-0.804,-2.067,-0.447091,-1.034917,-0.779667,-0.646667,-0.098333,-0.218667,Neg,1991-07-01
13,1992,0.073,-1.627,-1.010,-0.439,-2.032,-2.193,-0.566,-0.350,0.435,...,0.122,0.244,-0.718727,0.014083,-1.036333,0.079333,-1.207000,-1.160333,Pos,1992-07-01
14,1993,-2.021,0.437,-0.378,0.087,1.260,1.218,1.957,1.083,1.061,...,0.324,1.028,0.525091,0.573917,1.419333,0.711000,-0.446667,0.323000,Pos,1993-07-01
15,1994,0.723,1.157,0.693,-0.052,-0.153,-1.682,-0.492,1.910,-0.947,...,-0.793,0.933,-0.019455,0.258667,-0.088000,-0.772667,0.969333,0.162667,Pos,1994-07-01
16,1995,1.448,0.533,-0.154,0.649,1.397,-0.802,-3.010,-0.696,1.173,...,0.143,1.470,0.056727,0.018250,-1.502667,0.419667,0.971333,0.630667,Pos,1995-07-01
17,1996,0.332,-0.525,0.543,0.115,0.983,-0.252,0.021,-1.502,-1.314,...,-1.667,-0.023,-0.209091,-0.215083,-0.577667,-0.671667,0.425667,0.547000,Neg,1996-07-01
18,1997,0.369,-0.244,0.701,-0.458,1.028,-0.458,0.780,0.768,0.122,...,-1.905,-0.835,0.009818,0.232833,0.363333,-0.792667,0.034000,0.423667,Pos,1997-07-01
19,1998,0.413,0.390,0.736,1.927,-0.038,1.031,1.450,0.904,-0.122,...,0.817,1.435,0.718909,0.648500,1.128333,0.365000,-0.010667,0.875000,Pos,1998-07-01
20,1999,0.999,0.456,0.180,0.949,1.639,-1.325,0.316,0.042,-0.012,...,0.901,1.784,0.527091,0.682250,-0.322333,0.847333,0.963333,0.922667,Pos,1999-07-01
21,2000,1.273,0.620,0.133,0.233,1.127,0.117,0.059,-0.674,-1.853,...,-1.537,-1.290,-0.014091,-0.466667,-0.166000,-1.014333,1.225667,0.497667,Neg,2000-07-01
22,2001,-0.471,-0.265,-0.555,0.515,-0.262,0.386,-0.928,0.910,1.161,...,0.996,1.474,0.251273,0.116917,0.122667,1.144667,-0.675333,-0.100667,Pos,2001-07-01
23,2002,0.747,1.334,-1.823,0.165,-2.798,-1.112,-0.591,-0.099,-0.864,...,-0.924,1.308,-0.775364,-0.452750,-0.600667,-1.450667,1.185000,-1.485333,Neg,2002-07-01
24,2003,-0.988,-0.357,-0.188,0.224,0.385,-0.775,0.727,0.678,-0.323,...,-0.712,-1.323,-0.123091,0.073750,0.210000,-0.353333,-0.012333,0.140333,Pos,2003-07-01
25,2004,0.807,-1.182,0.432,0.151,0.460,1.195,1.474,-0.071,0.254,...,-0.242,-0.973,0.294182,0.025167,0.866000,-0.010000,-0.566000,0.347667,Pos,2004-07-01
26,2005,-0.129,1.243,0.158,0.355,-0.297,-1.428,-0.252,0.228,0.241,...,-0.551,-1.968,-0.036455,0.026833,-0.484000,-0.093000,0.047000,0.072000,Pos,2005-07-01
27,2006,0.339,-0.211,0.501,-0.169,1.695,0.438,0.926,-1.727,-0.324,...,0.101,0.638,0.222545,-0.244167,-0.121000,0.218667,-0.613333,0.675667,Neg,2006-07-01
28,2007,-0.083,0.075,-0.570,-1.035,-0.612,-1.198,-2.631,-0.108,0.031,...,-0.984,1.929,-0.686273,0.060833,-1.312333,-0.462333,0.210000,-0.739000,Pos,2007-07-01
29,2008,1.208,1.147,0.587,-0.873,-0.490,1.348,0.320,0.087,1.386,...,0.920,1.194,0.623182,0.497667,0.585000,1.173667,1.428000,-0.258667,Pos,2008-07-01
30,2009,0.963,0.456,0.605,0.029,-0.733,-0.470,-1.234,-0.686,-0.017,...,-1.915,0.607,-0.265182,-0.092917,-0.796667,-0.615667,0.871000,-0.033000,Neg,2009-07-01
31,2010,-0.757,-0.775,0.108,0.377,1.021,2.071,2.424,1.510,0.402,...,1.516,0.205,0.839273,0.709917,2.001667,1.084333,-0.308333,0.502000,Pos,2010-07-01
32,2011,0.052,1.074,-0.296,-0.870,1.266,-0.099,-1.384,-1.202,-1.250,...,-0.908,2.573,-0.293545,0.034500,-0.895000,-0.590000,0.443667,0.033333,Pos,2011-07-01
33,2012,1.583,-0.283,0.275,0.666,0.153,-0.197,1.259,0.489,0.562,...,-1.701,-0.764,0.214727,0.188583,0.517000,-0.527667,1.291000,0.364667,Pos,2012-07-01
34,2013,0.071,0.716,1.375,0.611,0.360,-0.271,0.945,-1.561,-1.658,...,0.189,0.061,0.029000,-0.113833,-0.295667,-0.642333,0.007667,0.782000,Neg,2013-07-01
35,2014,-0.683,0.322,0.467,0.614,-0.445,0.841,0.247,-0.059,-1.119,...,-0.519,1.322,-0.033909,0.387833,0.343000,-0.559000,-0.100000,0.212000,Pos,2014-07-01
36,2015,0.675,1.217,0.773,1.029,0.416,0.711,1.678,1.062,0.542,...,0.695,-0.059,0.784364,0.912083,1.150333,0.355667,1.071333,0.739333,Pos,2015-07-01
37,2016,1.392,1.093,2.038,0.097,0.012,2.565,0.407,-0.739,2.333,...,-1.508,-0.711,0.683000,0.081833,0.744333,0.216000,0.808667,0.715667,Pos,2016-07-01
38,2017,-0.982,-0.015,0.156,0.619,1.053,0.546,0.728,0.764,1.296,...,0.771,0.984,0.397091,0.431417,0.679333,0.499667,-0.569333,0.609333,Pos,2017-07-01
39,2018,1.275,1.041,0.141,-1.166,-0.077,-0.012,0.377,-0.343,1.458,...,0.991,0.930,0.383182,0.583417,0.007333,0.993000,1.100000,-0.367333,Pos,2018-07-01
40,2019,0.677,-0.500,0.745,0.336,0.335,1.465,-0.390,-1.080,0.563,...,-1.840,-1.360,-0.055818,-0.199083,-0.001667,-0.734000,0.369000,0.472000,Neg,2019-07-01
41,2020,-0.231,0.275,1.426,-0.475,0.577,1.071,-0.546,-0.720,0.194,...,0.813,1.481,0.331636,0.608750,-0.065000,0.757000,-0.438667,0.509333,Pos,2020-07-01
42,2021,1.045,1.344,0.086,0.827,0.314,1.203,-0.424,NaN,NaN,...,NaN,NaN,0.627857,NaN,0.389500,NaN,1.290000,0.409000,Pos,2021-07-01

In [192]:
display(kIndDf.getClimData())

mean SLP of {'lat': (-10, -50), 'lon': (165, 180)} 1012.8687
nan patching missing dates

[Timestamp('2021-08-01 00:00:00'),
 Timestamp('2021-09-01 00:00:00'),
 Timestamp('2021-10-01 00:00:00'),
 Timestamp('2021-11-01 00:00:00'),
 Timestamp('2021-12-01 00:00:00')]

     year    Annual                                                   \
               strp      stri       sps   soi       ipo          iod
0    1854       NaN       NaN       NaN   NaN -0.139000          NaN
1    1855       NaN       NaN       NaN   NaN  0.039909          NaN
2    1856       NaN       NaN       NaN   NaN -0.261455          NaN
3    1857       NaN       NaN       NaN   NaN -0.393545          NaN
4    1858       NaN       NaN       NaN   NaN  0.397455          NaN
..    ...       ...       ...       ...   ...       ...          ...
163  2017 -2.954545  0.941668  0.002695  0.11 -0.313727     0.377273
164  2018  0.227273 -0.453222  0.006032  0.07 -0.517091     0.287636
165  2019  0.227273  1.449203  0.008105 -0.81 -0.091273     0.660455
166  2020 -0.681818  1.751214  0.000330  0.31 -0.754455     0.194545
167  2021 -0.833333  0.408892       NaN   NaN -1.011571 -5453.889091

               Apr            ...    hydYrAvg           state            \
          aao strp      stri  ...         iod       aao  strp stri  sps
0         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
1         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
2         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
3         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
4         NaN  NaN       NaN  ...         NaN       NaN   NaN  NaN  NaN
..        ...  ...       ...  ...         ...       ...   ...  ...  ...
163  0.397091 -5.0 -0.588943  ...    0.215583  0.431417   Neg  Pos  Pos
164  0.383182  2.5 -1.095762  ...    0.490333  0.583417   Neg  Pos  Pos
165 -0.055818  0.0  3.179960  ...    0.511167 -0.199083   Pos  Neg  Pos
166  0.331636  2.5 -0.098447  ... -833.086750  0.608750   Neg  Pos  Pos
167  0.627857  2.5 -1.721084  ...         NaN       NaN   Neg  Pos  NaN

                             datetime
        soi  ipo  iod  aao
0       NaN  Neg  NaN  NaN 1854-07-01
1       NaN  Pos  NaN  NaN 1855-07-01
2       NaN  Neg  NaN  NaN 1856-07-01
3       NaN  Pos  NaN  NaN 1857-07-01
4       NaN  Neg  NaN  NaN 1858-07-01
..      ...  ...  ...  ...        ...
163  LaNina  Neg  Pos  Pos 2017-07-01
164  ElNino  Neg  Pos  Pos 2018-07-01
165  ElNino  Neg  Pos  Neg 2019-07-01
166  LaNina  Neg  Neg  Pos 2020-07-01
167  LaNina  Pos  Pos  Pos 2021-07-01

[168 rows x 135 columns]

In [193]:
kIndDf.getSelectSeries('DJF')

,strp,stri,sps,soi,ipo,iod,aao,datetime,year
0,NaN,NaN,NaN,NaN,0.191000,NaN,NaN,1854-07-01,1854
1,NaN,NaN,NaN,NaN,-0.396667,NaN,NaN,1855-07-01,1855
2,NaN,NaN,NaN,NaN,0.517333,NaN,NaN,1856-07-01,1856
3,NaN,NaN,NaN,NaN,-1.257333,NaN,NaN,1857-07-01,1857
4,NaN,NaN,NaN,NaN,0.213667,NaN,NaN,1858-07-01,1858
...,...,...,...,...,...,...,...,...,...
163,0.833333,0.233134,0.104909,-0.020000,-0.117333,-0.026667,-0.569333,2017-07-01,2017
164,-0.833333,-1.877906,0.011509,-0.046667,-1.039000,0.113000,1.100000,2018-07-01,2018
165,0.833333,1.119039,0.008966,-0.203333,0.020333,0.442333,0.369000,2019-07-01,2019
166,1.250000,1.488325,0.001636,-0.256667,-0.168333,0.228000,-0.438667,2020-07-01,2020
167,-1.250000,0.805882,NaN,1.880000,-1.218333,0.179667,1.290000,2021-07-01,2021

In [194]:
kIndDf.getSelectSeries('JJA')

,strp,stri,sps,soi,ipo,iod,aao,datetime,year
0,NaN,NaN,NaN,NaN,-0.132000,NaN,NaN,1854-07-01,1854
1,NaN,NaN,NaN,NaN,-0.140333,NaN,NaN,1855-07-01,1855
2,NaN,NaN,NaN,NaN,-0.502000,NaN,NaN,1856-07-01,1856
3,NaN,NaN,NaN,NaN,0.082000,NaN,NaN,1857-07-01,1857
4,NaN,NaN,NaN,NaN,0.818667,NaN,NaN,1858-07-01,1858
...,...,...,...,...,...,...,...,...,...
163,-3.333333,0.892430,0.004521,-0.123333,-0.305333,0.538333,0.679333,2017-07-01,2017
164,-0.833333,0.182405,0.002497,-0.533333,-0.347333,0.217667,0.007333,2018-07-01,2018
165,-1.666667,0.344654,0.008729,-0.953333,-0.201000,0.653333,-0.001667,2019-07-01,2019
166,0.000000,0.691563,NaN,-0.053333,-0.892333,0.305000,-0.065000,2020-07-01,2020
167,-2.500000,1.097582,NaN,NaN,-0.860000,-9999.000000,0.389500,2021-07-01,2021

In [195]:
kIndDf.getSelectSeries('hydYrAvg')

,strp,stri,sps,soi,ipo,iod,aao,datetime,year
0,NaN,NaN,NaN,NaN,-0.401417,NaN,NaN,1854-07-01,1854
1,NaN,NaN,NaN,NaN,0.235333,NaN,NaN,1855-07-01,1855
2,NaN,NaN,NaN,NaN,-0.739583,NaN,NaN,1856-07-01,1856
3,NaN,NaN,NaN,NaN,0.148250,NaN,NaN,1857-07-01,1857
4,NaN,NaN,NaN,NaN,-0.084250,NaN,NaN,1858-07-01,1858
...,...,...,...,...,...,...,...,...,...
163,-1.666667,1.323033,0.007588,0.355833,-0.775667,0.215583,0.431417,2017-07-01,2017
164,-1.666667,0.509853,0.006835,-0.437500,-0.034500,0.490333,0.583417,2018-07-01,2018
165,0.416667,-0.296005,0.002938,-0.543333,-0.266083,0.511167,-0.199083,2019-07-01,2019
166,-0.833333,2.183801,NaN,NaN,-1.150000,-833.086750,0.608750,2020-07-01,2020
167,-0.208333,0.718039,NaN,NaN,NaN,NaN,NaN,2021-07-01,2021

In [196]:
import os
os.remove("aao.csv") #take it off, default is SAM

In [197]:
#this should not work
kIndDf.getSelectSeries(series=['JJA'])

Exception: ('Expecting a string in series argument, recieved ', <class 'list'>)

In [ ]:
kIndDf.getSelectSeries(series='JJA')

In [ ]:
#this should not work as well
kIndDf = klimData.klimDataRetriever(hydroYearStartMonth='July')

In [ ]:
kIndDf = klimData.klimDataRetriever(hydroYearStartMonth='Jan',debug=True)
kIndDf.getSelectSeries()

In [ ]:
kIndDf = klimData.klimDataRetriever(hydroYearStartMonth='Sep',debug=True)
kIndDf.getSelectSeries()

In [ ]:
import os
os.remove("*.csv")